apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          imagePullPolicy: Never
          image: hubuspinovacao/backend:development
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30001
