apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          imagePullPolicy: Never
          image: hub_solus
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-env
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
